name: main

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "21f1002832@ds.study.iitm.ac.in"
        run: echo "Hello, world!"
